# Generated by Django 5.1.7 on 2025-05-15 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('SAE', 'SAE'), ('MINEDUC', 'Ayuda Mineduc')], max_length=10, verbose_name='Unidad')),
                ('official_id', models.IntegerField(choices=[(1, 'Funcionario SAE 1'), (2, 'Funcionario SAE 2'), (3, 'Funcionario SAE 3'), (4, 'Funcionario Ayuda Mineduc 1'), (5, 'Funcionario Ayuda Mineduc 2'), (6, 'Funcionario Ayuda Mineduc 3')], verbose_name='ID Funcionario')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora (UTC)')),
            ],
            options={
                'verbose_name': 'Registro de Atención',
                'verbose_name_plural': 'Registros de Atención',
                'ordering': ['-timestamp'],
            },
        ),
    ]
