# Generated by Django 4.2.7 on 2026-04-09 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('SAE', 'SAE'), ('MINEDUC', 'Ayuda Mineduc'), ('BECAS', 'Becas')], max_length=10, verbose_name='Unidad')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora (UTC)')),
            ],
            options={
                'verbose_name': 'Registro de Recepción',
                'verbose_name_plural': 'Registros de Recepción',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='atencion',
            name='official_id',
            field=models.IntegerField(choices=[(1, 'Funcionario SAE 1 (MODULO 1)'), (2, 'Funcionario SAE 2 (MODULO 2)'), (3, 'Funcionario SAE 3 (MODULO 3)'), (4, 'Funcionario Ayuda Mineduc 1 (MODULO 4)'), (5, 'Funcionario Ayuda Mineduc 2 (MODULO 5)'), (6, 'Funcionario Ayuda Mineduc 3 (MODULO 6)'), (7, 'Funcionario Becas 1 (MODULO 7)'), (8, 'Funcionario Becas 2 (MODULO 8)'), (9, 'Funcionario Becas 3 (MODULO 9)')], verbose_name='ID Funcionario'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='unit',
            field=models.CharField(choices=[('SAE', 'SAE'), ('MINEDUC', 'Ayuda Mineduc'), ('BECAS', 'Becas')], max_length=10, verbose_name='Unidad'),
        ),
    ]
