# Generated by Django 4.2.7 on 2026-04-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_alter_atencion_official_id'),
        ('turnos', '0002_recepcion_alter_atencion_official_id_and_more'),
    ]

    operations = [
    ]
