# Generated by Django 4.2.7 on 2026-04-27 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_recepcion_alter_atencion_official_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAtencionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('SAE', 'SAE'), ('MINEDUC', 'Ayuda Mineduc'), ('BECAS', 'Becas')], max_length=10, verbose_name='Unidad')),
                ('official_id', models.IntegerField(choices=[(1, 'Funcionario SAE 1 (MODULO 1)'), (2, 'Funcionario SAE 2 (MODULO 2)'), (3, 'Funcionario SAE 3 (MODULO 3)'), (4, 'Funcionario Ayuda Mineduc 1 (MODULO 4)'), (5, 'Funcionario Ayuda Mineduc 2 (MODULO 5)'), (6, 'Funcionario Ayuda Mineduc 3 (MODULO 6)'), (7, 'Funcionario Becas 1 (MODULO 7)'), (8, 'Funcionario Becas 2 (MODULO 8)'), (9, 'Funcionario Becas 3 (MODULO 9)')], verbose_name='ID Funcionario')),
                ('nombre_usuario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Usuario')),
                ('rut_usuario', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT')),
                ('tramite', models.CharField(choices=[('cambio_establecimiento', 'Cambio de establecimiento'), ('solicita_establecimiento', 'Solicita establecimiento'), ('reclamo', 'Reclamo'), ('consulta_general', 'Consulta general'), ('otro', 'Otro')], max_length=50, verbose_name='Trámite')),
                ('respuesta', models.CharField(choices=[('realizo_solicitado', 'Realizó lo solicitado'), ('no_disponible', 'Solicitud no disponible'), ('se_deriva', 'Se deriva'), ('informacion_entregada', 'Información entregada'), ('otro', 'Otro')], max_length=50, verbose_name='Respuesta')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora (UTC)')),
            ],
            options={
                'verbose_name': 'Detalle de Atención',
                'verbose_name_plural': 'Detalles de Atención',
                'ordering': ['-timestamp'],
            },
        ),
    ]
