# Generated by Django 4.2.7 on 2026-05-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_registroatenciondetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroatenciondetalle',
            name='nombre_usuario',
        ),
        migrations.RemoveField(
            model_name='registroatenciondetalle',
            name='rut_usuario',
        ),
        migrations.AddField(
            model_name='registroatenciondetalle',
            name='menores_data',
            field=models.JSONField(blank=True, help_text='Lista de menores [{rut, curso}]', null=True, verbose_name='Datos de Menores'),
        ),
        migrations.AddField(
            model_name='registroatenciondetalle',
            name='nombre_apoderado',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Apoderado'),
        ),
        migrations.AddField(
            model_name='registroatenciondetalle',
            name='rut_apoderado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT Apoderado'),
        ),
        migrations.AddField(
            model_name='registroatenciondetalle',
            name='telefono_apoderado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Apoderado'),
        ),
        migrations.AlterField(
            model_name='registroatenciondetalle',
            name='tramite',
            field=models.CharField(choices=[('cambio_establecimiento', 'Cambio de establecimiento'), ('solicita_establecimiento', 'Solicita establecimiento'), ('cambio_nivel', 'Cambio de nivel'), ('apoyo_plataforma', 'Apoyo en uso de plataforma'), ('reclamo', 'Reclamo'), ('consulta_general', 'Consulta general'), ('otro', 'Otro')], max_length=50, verbose_name='Trámite'),
        ),
    ]
