# Generated by Django 4.2.7 on 2026-04-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_merge_20260416_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='official_id',
            field=models.IntegerField(choices=[(1, 'Funcionario SAE 1 (MODULO 1)'), (2, 'Funcionario SAE 2 (MODULO 2)'), (3, 'Funcionario SAE 3 (MODULO 3)'), (4, 'Funcionario Ayuda Mineduc 1 (MODULO 4)'), (5, 'Funcionario Ayuda Mineduc 2 (MODULO 5)'), (6, 'Funcionario Ayuda Mineduc 3 (MODULO 6)'), (7, 'Funcionario Becas 1 (MODULO 7)'), (8, 'Funcionario Becas 2 (MODULO 8)'), (9, 'Funcionario Becas 3 (MODULO 9)')], verbose_name='ID Funcionario'),
        ),
    ]
